---
blank_issues_enabled: false
contact_links:
  - name: PyGraphSheets Community Support
    url: https://github.com/Luis-Rosario-Alers/PyGraphSheets/discussions
    about: Please ask and answer questions here.
